export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAILED = 'GET_ALL_CATEGORY_FAILED';
export const GET_PRODUCT_BY_CATEGORY_SUCCESS =
  'GET_PRODUCT_BY_CATEGORY_SUCCESS';
export const GET_PRODUCT_BY_CATEGORY_FAILED = 'GET_PRODUCT_BY_CATEGORY_FAILED';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAILED = 'GET_PRODUCT_BY_ID_FAILED';
export const GET_PRODUCT_BEST_SELL_SUCCESS = 'GET_PRODUCT_BEST_SELL_SUCCESS';
export const GET_PRODUCT_BEST_SELL_FAILED = 'GET_PRODUCT_BEST_SELL_FAILED';
